language: none
sudo: required
dist: xenial

install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -q
 - sudo apt-get install -y qt5-default qttools5-dev-tools 
 - sudo apt-get install -y libqt5multimedia5 qtmultimedia5-dev
 - sudo apt-get install -y g++-5
 - sudo apt-get install -y gcc-5
 - sudo apt-get install libevent-2.0-5 libevent-dev
env: COMPILER_NAME=g++-5 CXX=g++-5 CC=gcc-5
script: 
   - qmake -qt=qt5 -v
   - qmake -qt=qt5 QMAKE_CXX=g++-5
   - g++ -v
   - gcc -v
   - g++-5 -v
   - gcc-5 -v
   - make
